# ==========================================
#    Skyfall Proxy Configuration
# ==========================================
listeners:
  - query_port: 25577
    motd: '&6&lSkyfall Proxy\n&7¡Bienvenido al servidor!'
    tab_list: GLOBAL_PING
    query_enabled: false
    proxy_protocol: false
    ping_passthrough: false
    priorities:
      - lobby
    bind_local_address: true
    host: 0.0.0.0:25577
    max_players: 100
    tab_size: 60
    force_default_server: false
    forced_hosts:
      pvp.example.com: pvp
      lobby.example.com: lobby
servers:
  lobby:
    motd: '&aServidor Lobby'
    address: localhost:25565
    restricted: false
groups:
  admin:
    - bungeecord.command.alert
    - bungeecord.command.end
    - bungeecord.command.ip
    - bungeecord.command.reload
  user:
    - bungeecord.command.server
    - bungeecord.command.list
    - bungeecord.command.send
connection_throttle: 4000
connection_throttle_limit: 3
timeout: 30000
log_commands: false
log_pings: true
online_mode: true
ip_forward: true
network_compression_threshold: 256
player_limit: -1
prevent_proxy_connections: false
disabled_commands:
  - disabledcommandhere
forge_support: false
inject_commands: false
stats: 7e84d11e-a4dd-4da8-b7e0-c6c8c26e9f4f